# Site settings
title: UTM VM Installation Guides
description: Installation guides for security VMs on Apple Silicon Macs
url: https://vexedmouse09.github.io
baseurl: "/UDMCyberSecurity-Labs-MacBookCompatibility"

# Theme settings
theme: jekyll-theme-minimal
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# Build settings
markdown: kramdown
highlighter: rouge

# GitHub Pages settings
github:
  is_project_page: true
  repository_url: https://github.com/vexedmouse09/UDMCyberSecurity-Labs-MacBookCompatibility
