# Site settings
title: UTM VM Installation Guides
description: Installation guides for security VMs on Apple Silicon Macs
url: https://vexedmouse09.github.io
baseurl: "/UDMCyberSecurity-Labs-MacBookCompatibility"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.4.0
color_scheme: dracula

# Just the Docs settings
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/vexedmouse09/UDMCyberSecurity-Labs-MacBookCompatibility"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Footer content
footer_content: "Copyright &copy; 2025. Distributed under the MIT license."
