# Site settings
title: UTM VM Installation Guides
description: Installation guides for security VMs on Apple Silicon Macs
url: https://vexedmouse09.github.io
baseurl: "/UDMCyberSecurity-Labs-MacBookCompatibility"

include:
  - _includes

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.4.2

# Theme settings
color_scheme: dark
search_enabled: true
heading_anchors: true

# Navigation settings
aux_links:
  "GitHub Repository":
    - "https://github.com/vexedmouse09/UDMCyberSecurity-Labs-MacBookCompatibility"

# Enable built-in collapsible navigation
nav_fold:
  auto: true  # Auto-collapse inactive sections

enable_copy_code_button: true

# Footer content
footer_content: "Copyright &copy; 2025. Distributed under the MIT license."

# Enable callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green

# Search settings
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  tokenizer_separator: /[\s/]+/


after_footer_scripts:
  - /assets/js/custom.js
