# Site settings
title: UTM VM Installation Guides
description: Installation guides for security VMs on Apple Silicon Macs
url: https://vexedmouse09.github.io
baseurl: "/UDMCyberSecurity-Labs-MacBookCompatibility"

# Build settings
markdown: kramdown
remote_theme: just-the-docs/just-the-docs@v0.4.2
color_scheme: dark

# Just the Docs settings
search_enabled: true
heading_anchors: true
aux_links:
  "GitHub Repository":
    - "https://github.com/vexedmouse09/UDMCyberSecurity-Labs-MacBookCompatibility"

# Enable collapsible navigation
collapse_navigation: true

# Enable mermaid diagrams
mermaid:
  # Version of mermaid library
  version: "9.1.6"
  # Set to true to initialize mermaid
  initialize: true

# Footer content
footer_content: "Copyright &copy; 2025. Distributed under the MIT license."

# Custom callouts
callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
