# Site settings
title: UTM VM Installation Guides
description: Installation guides for security VMs on Apple Silicon Macs
url: https://vexedmouse09.github.io
baseurl: "/UDMCyberSecurity-Labs-MacBookCompatibility"

# Theme settings
remote_theme: "dracula/gh-pages"

# Just the Docs settings
search_enabled: true
heading_anchors: true
aux_links:
  "View on GitHub":
    - "https://github.com/vexedmouse09/UDMCyberSecurity-Labs-MacBookCompatibility"
